<?php

/**
 * BaseContacto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $email
 * @property string $telefono
 * @property string $asunto
 * @property string $mensaje
 * 
 * @method string   getNombre()   Returns the current record's "nombre" value
 * @method string   getEmail()    Returns the current record's "email" value
 * @method string   getTelefono() Returns the current record's "telefono" value
 * @method string   getAsunto()   Returns the current record's "asunto" value
 * @method string   getMensaje()  Returns the current record's "mensaje" value
 * @method Contacto setNombre()   Sets the current record's "nombre" value
 * @method Contacto setEmail()    Sets the current record's "email" value
 * @method Contacto setTelefono() Sets the current record's "telefono" value
 * @method Contacto setAsunto()   Sets the current record's "asunto" value
 * @method Contacto setMensaje()  Sets the current record's "mensaje" value
 * 
 * @package    navtur
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContacto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contacto');
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('telefono', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('asunto', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('mensaje', 'string', 2500, array(
             'type' => 'string',
             'length' => 2500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}