<?php

/**
 * BaseContacto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $ap_paterno
 * @property string $ap_materno
 * @property string $telefono
 * @property string $email
 * @property string $direccion
 * @property string $empresa
 * 
 * @method string   getNombre()     Returns the current record's "nombre" value
 * @method string   getApPaterno()  Returns the current record's "ap_paterno" value
 * @method string   getApMaterno()  Returns the current record's "ap_materno" value
 * @method string   getTelefono()   Returns the current record's "telefono" value
 * @method string   getEmail()      Returns the current record's "email" value
 * @method string   getDireccion()  Returns the current record's "direccion" value
 * @method string   getEmpresa()    Returns the current record's "empresa" value
 * @method Contacto setNombre()     Sets the current record's "nombre" value
 * @method Contacto setApPaterno()  Sets the current record's "ap_paterno" value
 * @method Contacto setApMaterno()  Sets the current record's "ap_materno" value
 * @method Contacto setTelefono()   Sets the current record's "telefono" value
 * @method Contacto setEmail()      Sets the current record's "email" value
 * @method Contacto setDireccion()  Sets the current record's "direccion" value
 * @method Contacto setEmpresa()    Sets the current record's "empresa" value
 * 
 * @package    navtur
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContacto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contacto');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ap_paterno', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ap_materno', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('telefono', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('direccion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('empresa', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}