<?php

/**
 * BaseNoticia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property string $cuerpo
 * @property string $imagen
 * @property string $autor
 * @property string $lugar
 * @property date $fecha
 * 
 * @method string  getTitulo() Returns the current record's "titulo" value
 * @method string  getCuerpo() Returns the current record's "cuerpo" value
 * @method string  getImagen() Returns the current record's "imagen" value
 * @method string  getAutor()  Returns the current record's "autor" value
 * @method string  getLugar()  Returns the current record's "lugar" value
 * @method date    getFecha()  Returns the current record's "fecha" value
 * @method Noticia setTitulo() Sets the current record's "titulo" value
 * @method Noticia setCuerpo() Sets the current record's "cuerpo" value
 * @method Noticia setImagen() Sets the current record's "imagen" value
 * @method Noticia setAutor()  Sets the current record's "autor" value
 * @method Noticia setLugar()  Sets the current record's "lugar" value
 * @method Noticia setFecha()  Sets the current record's "fecha" value
 * 
 * @package    navtur
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNoticia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('noticia');
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('cuerpo', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10000,
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('autor', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('lugar', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}