<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/16 18:30:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=navtur',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
