<?php

/**
 * ServicioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Servicio');
    }
}