generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Noticia
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          noticia
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        titulo: {label: 'TITULO'}
        cuerpo: {label: 'CUERPO'}
        imagen: {label: 'IMAGEN'}
        autor:  {label: 'AUTOR'}
        lugar:  {label: 'LUGAR'}
        fecha:  {label: 'FECHA', date_format: 'dd/MM/yyyy'}
      list:    
        title: Todas las noticias registradas
        display: [fecha, titulo, autor, lugar]
        object_actions: ~
      filter:  
        display: [titulo, autor, fecha]
      form:    
        display:
          Esta noticia se mostrara en la página web: [titulo, autor, fecha, lugar, imagen, cuerpo]
      edit:    
        title: Editar Noticia %%titulo%%
        actions: ~
      new:     
        title: Nueva Noticia
        actions:
          _list: ~
          _save: ~
