generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Contacto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contacto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        nombre:     {label: 'NOMBRE'}
        email:      {label: 'EMAIL'}  
        telefono:   {label: 'TELEFONO'}  
        asunto:     {label: 'ASUNTO'}  
        mensaje:    {label: 'MENSAJE'}  
        created_at: {label: 'FECHA', date_format: 'dd/MM/yyyy'}
      list:    
        title: Estas Personas y Empresas quieren Contactarte
        display: [created_at, nombre,	email, telefono, asunto]
        object_actions: 
          _edit: ~
        actions: []
      filter:  
        display: [nombre]
      form:    ~
      edit:    
        title: Este es el mensaje que te mandó
        actions:
          _list: ~
      new:     ~
