generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Contacto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contacto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  
        display: [empresa, nombre, ap_paterno, ap_materno]
      form:    ~
      edit:    ~
      new:     ~
